### ISSUE TITLE
Both websites are having issues

### ISSUE THREAD

**Issue by TessMyers** [RegExpress/regexpress#150]
After no apparent change to the code, both the test website (http://regexpress-test.cloudapp.net/) and the main website ( regexpress.io ) are having issues. Regexpress.io fails to load as per https://github.com/RegExpress/regexpress/issues/148, and the test website's undo button is not working as well as per https://github.com/RegExpress/regexpress/issues/149. 

The most recent commit was my update to add ng-cloak + tag most recent version. ng-cloak has not taken effect on either website, so it's likely that the issue stems from that update, or the tagging process. Interestingly, both websites appeared to work for several weeks after this update. 

At this point, I think it would make sense to revert back to before that most recent commit. Thoughts?

**Comment by mihoward21** [comment]
i agree, something is very wrong. can we revert back and see if that fixes it?

from the most recent commit, the only thing i saw that maybe could have had an impact was the order in which the js files are included has changed.
https://github.com/RegExpress/regexpress/commit/1b84ef9759c615d229b83935b75e8d1fa12d159b

maybe its possible that one file is depending on another which is now being loaded after?

**Comment by tgrrtt** [comment]
Im not sure about staging, but updating prod should be a fairly straight foward manner.
Checkout the last commit or tag that worked. Re-tag it as 1.whatever-fix
Push that back up to github.

**Comment by TessMyers** [comment]
Would one of you be willing to spearhead this? I've got a whole lot on my plate at the moment.

**Comment by tgrrtt** [comment]
I pushed to prod again last night. Things seem to be working now. I reverted to commit 86954f245 , as that was the last release that was in production.

**Comment by TessMyers** [comment]
Beautiful. That has fixed all the problems with regexpress.io for me, though I am still unable to use the 'undo' button on the test website. Are either of you experiencing that problem?

**Comment by tgrrtt** [comment]
I didn't update staging, so that should still be broken.
